nasa-jpl/explorer-1

- .github/workflows/update-release-draft.yml
Closes #102 
The removal of these values in the `update-release-draft.yml` workflow should let Release Drafter use the standard `name-template`, …
> Remove prerelease overrides for Release Drafter

- .github/ISSUE_TEMPLATE/feature-request.md
Fixes formatting of labels. See https://github.community/t/apply-labels-automatically-at-issue-creation/1218/17
Merge and hopefully the feature request …
> Issue templates: fixing labels in "Feature request" template

- CONTRIBUTING.md
- LICENSE
Correcting our oversight in the 1.0 release.
> Add LICENSE file and terms for contributing

- package-lock.json
- package.json
Updates the package version to `1.1.0`
> Updating the package version before publishing to npm

- src/scss/_typography.scss
Tweak H1 font sizes per this morning's discussion with @gekim84.
1. `npm run storybook`
2. http://localhost:6006/?path=/docs/foundation-typography--text- …
> Adjust H1 sizes to be less of a dramatic jump from H2

- storybook/stories/_docs/overviews/global_footers.docs.mdx
- storybook/stories/_docs/utils/ComponentItem.jsx
Fixes broken links in our hosted Storybook: https://nasa-jpl.github.io/explorer-1/ (a regression from #428)
1. `npm run build-storybook`
2. `python3 -m …
> fix: links to stories within storybook

- packages/vue/src/docs/foundation/DynamicTokens.vue
Fixing some copy/paste typos in the Dynamic Tokens Storybook story.
> fixing names of dynamic tokens in storybook

- apps/vue-storybook/package.json
- package.json
- packages/common-storybook/package.json
- packages/common/package.json
- packages/html/package.json
- packages/nuxt/package.json
- packages/vue/package.json
> bumping package versions before publishing

- apps/vue-storybook/.storybook/preview.ts
- packages/vue/src/components/HeroLarge/HeroLarge.stories.js
- packages/vue/src/components/HeroListingIndex/HeroListingIndex.stories.js
- packages/vue/src/components/HeroMedia/HeroMedia.stories.js
- packages/vue/src/components/HeroMedium/HeroMedium.stories.js
- packages/vue/src/components/HeroMedium/HeroSmall.stories.js
- packages/vue/src/docs/overviews/heroes.docs.mdx
Cleans up story names for hero components in Storybook.
2. View this section: …
> chore: clarifying story names for hero components

- apps/html-storybook/package.json
- apps/vue-storybook/package.json
- package.json
- packages/common-storybook/package.json
- packages/common/package.json
- packages/configs/eslint/package.json
- packages/configs/prettier/package.json
- packages/configs/tsconfig/package.json
- packages/html/package.json
- packages/nuxt/package.json
- packages/vue/package.json
> Bumping to v3.1.1

- apps/vue-storybook/package.json
- package.json
- packages/common/package.json
- packages/vue/package.json
> bumping to version to 3.1.2

- apps/vue-storybook/package.json
- package.json
- packages/common-storybook/package.json
- packages/html/package.json
- packages/vue/package.json
> chore: bumping to version 3.1.3

- packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
- packages/vue/src/components/BlockLinkTile/BlockLinkTile.vue
Supports https://github.com/nasa-jpl/www/issues/243
- adds EDU styles for LinkCard and LinkTile
2. View …
> fix: updating EDU styles for LinkCard and LinkTile

- packages/vue/package.json
bumping @explorer-1/vue package to 0.1.8
> bumping @explorer-1/vue package to 0.1.8

- packages/vue/src/components/TheFooter/TheFooter.vue
Addresses feedback in https://github.com/nasa-jpl/www/issues/189#issuecomment-2254303250
2. View …
> fix: alignment in TheFooter, adding custom copy for EDU footer

- packages/vue/src/components/BaseTag/BaseTag.vue
- packages/vue/src/components/DetailHeadline/DetailHeadline.stories.js
- packages/vue/src/components/DetailHeadline/DetailHeadline.vue
- packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
Supports https://github.com/nasa-jpl/www/issues/282
Supports https://github.com/nasa-jpl/www/issues/97
Supports …
> fix: Explainer Articles

- packages/common/tailwind.colors.ts
- packages/vue/src/components/NavDesktop/NavDesktopDropdown.vue
- packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.stories.js
- packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
- packages/vue/src/components/NavHeading/NavHeading.stories.js
- packages/vue/src/components/NavHeading/NavHeading.vue
- packages/vue/src/components/NavLinkList/NavLinkList.vue
- packages/vue/src/components/NavMobile/NavMobile.vue
- packages/vue/src/components/TheFooter/TheFooter.vue
Addresses https://github.com/nasa-jpl/www/issues/189#issuecomment-2271719519
- Fixes alignment in `NavHeading`
- Fixes definition of `lighter` color …
> fix: header and footer feedback

- packages/vue/src/components/CalendarButton/CalendarButton.vue
- packages/vue/src/components/MetadataEvent/MetadataEvent.vue
- packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.stories.js
- packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
- packages/vue/src/utils/dayjs.js
- packages/vue/src/utils/rangeifyGrades.ts
Addresses https://github.com/nasa-jpl/www/issues/319 and the FE portion of https://github.com/nasa-jpl/www/issues/368
- Does not show time if EDU Event …
> fix: event detail page when there are no times, remove ics button for ongoing events

- packages/vue/src/components/BaseImageCaption/BaseImageCaption.vue
- packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue
- packages/vue/src/components/BlockGist/BlockGist.stories.js
- packages/vue/src/components/BlockGist/BlockGist.vue
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
- packages/vue/src/components/BlockTeaser/BlockTeaser.vue
- packages/vue/src/components/NavDesktop/NavDesktop.stories.js
- packages/vue/src/components/NavHeading/NavHeading.vue
- packages/vue/src/components/NavLinkList/NavLinkList.stories.js
- packages/vue/src/components/TheFooter/TheFooter.vue
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
Address feedback in https://github.com/nasa-jpl/www/issues/364
Fixes https://github.com/nasa-jpl/www/issues/390
Fixes …
> fix: EDU Explainer Article and Header/Footer alignment

- .github/workflows/storybook.yml
- packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue
- packages/vue/src/components/NavSecondary/NavSecondaryDropdown.vue
- packages/vue/src/components/NavSecondary/NavSecondaryLink.vue
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
- packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
- packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
Additional follow up to https://github.com/nasa-jpl/www/issues/364#issuecomment-2300018343
> fix: adjustments to NavJumpMenu

- packages/vue/src/components/BaseAccordionItem/BaseAccordionItem.vue
- packages/vue/src/components/BlockAccordion/BlockAccordion.stories.js
- packages/vue/src/components/BlockAccordion/BlockAccordion.vue
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
Completes https://github.com/nasa-jpl/www/issues/379
2. View the BlockAccordion story: …
> feature: BlockAccordion

- packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.stories.js
- packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.vue
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
- packages/vue/src/components/MetadataEduResource/MetadataEduResource.stories.js
- packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
- packages/vue/src/components/SearchSelectMenu/SearchSelectMenu.vue
- packages/vue/src/interfaces.ts
- packages/vue/src/utils/rangeifyGrades.ts
Supports
- https://github.com/nasa-jpl/www/issues/229
- https://github.com/nasa-jpl/www/issues/227
This PR:
- Adds new component `BlockLinkCardList`
- …
> feature: add BlockLinkCardList and BlockLinkCarousel to BlockStreamfield

- packages/common/src/scss/components/_BlockText.scss
- packages/vue/src/components/AboutTheAuthor/AboutTheAuthor.stories.js
- packages/vue/src/components/AboutTheAuthor/AboutTheAuthor.vue
- packages/vue/src/components/BlockText/BlockText.vue
- packages/vue/src/components/DetailHeadline/DetailHeadline.vue
- packages/vue/src/interfaces.ts
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
- packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
- packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
- packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.stories.js
- packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
- packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js
- packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Supports https://github.com/nasa-jpl/www/issues/82
- Adds `AboutTheAuthor` component
- Adds above component to `PageEduNewsDetail`, `PageEduLesson`, and …
> feature: adding AboutTheAuthor component, and adding to relevant templates

- packages/vue/src/components/MetaPanel/MetaPanel.stories.js
- packages/vue/src/components/MetaPanel/MetaPanel.vue
- packages/vue/src/components/MetaPanelItems/MetaPanelItems.vue
- packages/vue/src/utils/rangeifyGrades.ts
Fixes from https://github.com/nasa-jpl/www/issues/190#issuecomment-2303783655
2. view the MetaPanel story
> qa fixes to MetaPanel

- packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
- packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
- packages/vue/src/components/MetadataEvent/MetadataEvent.stories.js
Addresses feedback in https://github.com/nasa-jpl/www/issues/229 and https://github.com/nasa-jpl/www/issues/191
2. View …
> fixes: BlockLinkCardList and Card metadata

- packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.stories.js
- packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue
Resolves qa feedback from: https://github.com/nasa-jpl/www/issues/103#issuecomment-2313883916
- Adds share buttons
- Confirms show/hide MetaPanel …
> fixes: collection detail page

- packages/vue/src/components/BlockDialog/BlockDialog.vue
- packages/vue/src/components/NavDesktop/NavDesktop.vue
- packages/vue/src/components/NavSearchForm/NavSearchForm.vue
> removing some stray console.log outputs

- packages/vue/src/components/BlockIframeEmbed/BlockIframeEmbed.vue
Addresses iframe feedback in https://github.com/nasa-jpl/www/issues/99
> disabling dark background in iframe embeds for EDU

- packages/vue/src/components/FormContact/FormContact.vue
puts contact form back to google form solution for now
http://localhost:6006/?path=/story/components-forms-formcontact--base-story
> fix: migrate contact form back to google endpoint, works in storybook

- packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
- packages/vue/src/constants.ts
Tweaks to how filter labels are rendered in search.
> cleaning up search filter names between EDU and WWW

- apps/vue-storybook/.storybook/preview.ts
- apps/vue-storybook/package.json
- packages/vue/package.json
- packages/vue/src/components/MissionDetailAbout/MissionDetailAbout.vue
- packages/vue/src/components/MissionDetailHighlights/MissionDetailHighlights.vue
- packages/vue/src/components/TopicDetailMore/TopicDetailMoreVisibility.vue
- pnpm-lock.yaml
Replaces `vue-observe-visibility` with `vue3-observe-visibility`. This fixes animations/visibility in the components that use callbacks on intersection …
> fix: replace vue-observe-visibility with vue3-observe-visibility

- packages/vue/src/components/BaseButton/BaseButton.vue
- packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
- packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
- packages/vue/src/components/SearchResultCard/SearchResultCard.vue
- packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
- packages/vue/src/components/SearchResultsList/SearchResultsList.vue
- packages/vue/src/interfaces.ts
Missed a spot in #596
Also addresses feedback from:
- https://github.com/nasa-jpl/www/issues/272#issuecomment-2330342477
> fixing /home/ prefix, Search filter behavior tweaks

- packages/vue/src/components/BaseButton/BaseButton.vue
> fixes setting both href and to in BaseButton's NuxtLink

- packages/vue/src/components/MetaPanel/MetaPanel.vue
- packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
- https://github.com/nasa-jpl/www/issues/99#issuecomment-2338655736
Fixes:
- Updates headings for each Standards type
- Fixes type …
> fix: fixing standards headings and math standards in EDU Lesson template

- apps/vue-storybook/.storybook/preview.ts
- packages/vue/src/components/HeroMedia/HeroMedia.vue
- packages/vue/src/interfaces.ts
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
- packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
- packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
- packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
- packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.stories.js
- packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue
- packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js
- packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/360
Changes:
- The main EDU resources now use the same hero configuration/logic
- Explainer Article …
> feature: making hero configuration the same between main EDU resources

- packages/vue/src/components/SearchResultsList/SearchResultsList.vue
> removing domain from search results urls to ensure router links

- apps/vue-storybook/.storybook/_mock-components.js
- packages/vue/src/templates/www/PageAsteroidWatchContent/PageAsteroidWatchContent.vue
- sets `PageAsteroidWatchContent` to use `FetchAsteroidWatchWidget`. Was originally using `AsteroidWatchWidget` which doesn't fetch any data
1. Not a …
> fix: using FetchAsteroidWatchWidget

- packages/vue/src/components/NavSearchForm/NavSearchForm.vue
- https://github.com/nasa-jpl/www/issues/110#issuecomment-2370113337
Pairs with this www change: …
> fixing edu path in NavSearchForm

- packages/common/src/scss/components/_BlockRichTable.scss
- packages/vue/src/components/BlockRichTable/BlockRichTable.vue
- packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
Fixes markup of the table caption for accessibility. The previous version was also causing hydration errors.
2. view …
> fix: markup for table caption

- packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue
Fixes
- https://github.com/nasa-jpl/explorer-1/issues/638
Changes
- it was assumed that `to-black` would work for all viewports. However, since …
> fix: www homepage background gradient

- packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
- https://github.com/nasa-jpl/www/issues/217#issuecomment-2372154363
Changes:
- adds `overflow-hidden` to each step container to …
> fixing rich text media in student project steps

- packages/common/src/scss/components/_BlockText.scss
- packages/vue/src/components/BlockText/BlockText.stories.js
- packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
- https://github.com/nasa-jpl/www/issues/217#issuecomment-2387310653
Fixes:
- https://github.com/nasa-jpl/explorer-1/issues/648
Code …
> fixes: lists with floating images, headings in BlockText

- packages/vue/src/utils/mixins.ts
Addresses the frontend part of:
- https://github.com/nasa-jpl/www/issues/673#issuecomment-2407687592
I think it would be much easier to test this on dev …
> fix: adding logic to use the end date in calendar chip if event is upcoming

- packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/696
Changes:
- adds logic to PageEduCollectionsDetail to only add margin-bottom to the hero if there …
> fixing spacing below collections hero when there is a secondary nav

- packages/vue/src/components/FormNewsletterSignup/FormNewsletterSignup.vue
> fix: Update FormNewsletterSignup.vue - fix regex

- packages/vue/src/components/SearchInput/SearchInput.vue
- packages/vue/src/components/TheFooter/TheFooterSignUp.vue
> Fix: revert input zoom fix

- packages/vue/src/templates/PageContent/PageContent.vue
- packages/vue/src/templates/edu/PageContentEdu.stories.js
Addresses:
- https://github.com/nasa-jpl/www/issues/611
2. view the story: …
> fix: adding hero title option to PageContent template

- .changeset/thirty-apes-work.md
- packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/754
Changes:
- Removes `overflow-x-hidden` from wrapping div as it was breaking the …
> fixing anchor links on EDU Lesson pages

- apps/vue-storybook/.percy.yml
Testing workaround suggested in https://github.com/percy/percy-storybook/issues/1008\#issuecomment-2472687058
Keeping this PR as a draft until our Percy quota resets.
> fix: flaky percy tests

- .changeset/lucky-zebras-yell.md
- packages/vue/src/templates/PageContent/PageContent.stories.js
- packages/vue/src/templates/PageContent/PageContent.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/772
Changes:
- checks for `showShareLinks` in `PageContent`
2. view the two …
> feature: show/hide share links

- packages/vue/src/templates/PageNewsDetail/PageNewsDetail.stories.js
- packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/772#issuecomment-2518686093
Changes:
- Adds logic to make share links optional on WWW news pages
1. …
> adding showShareLinks logic to news pages

- packages/vue/src/templates/PageNewsDetail/PageNewsDetail.stories.js
- packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/772
Revises #711 to use `hideShareLinks` instead of `showShareLinks`. 
2. …
> fix: changing showShareLinks to hideShareLinks on news detail pages

- apps/vue-storybook/vite.config.ts
- packages/common-storybook/src/plugins/package-versions.js
- packages/common/package.json
- packages/html/package.json
- packages/vue/package.json
- packages/vue/src/docs/introduction.docs.mdx
adds current versions of @explorer-1/vue and @explorer-1/common that are being used in the Storybook to appear on the introduction page.
> adding version numbers to docs
