storybook/stories/_docs/gettingstarted_developer.stories.mdx
Fixing a broken link to the repo README from the Getting Started Guide for Developers. Previously the link was pointing to a 404 due to a stray `@`. …
=> Docs: Fixing the link to the Explorer 1 readme

tailwind.config.js
darkMode: 'class',
[Now that dark mode is a first-class feature of many operating systems, it’s becoming more and more common to design a dark version of your website to go along with the default design. it's now supported fully in the tailwind typography library](https://tailwindcss.com/docs/dark-mode)
=> Update Tailwind config to not activate dark mode based on user's OS-level setting

.pre-commit-config.yaml, package-lock.json, package.json
Reverts https://github.com/nasa-jpl/explorer-1/pull/184 to fix the Storybook HTML addon. The HTML tab in the compiled Storybook was missing, and upon …
=> Revert prettier to v2.5.1 to fix Storybook HTML addon

package.json
This PR removes the engines added in https://github.com/nasa-jpl/explorer-1/pull/186. We only really need them defined in `.nvmrc` for our actions to …
=> Removing engines defined in package.json

src/scss/_typography.scss
I discovered an issue with our current heading styling while working on nasa-jpl/www-frontend#1396: The tighter tracking on bare heading elements `h1`, …
=> Set `tracking-normal` explicitly on H4 and H5 styles

storybook/stories/components/BlockImageCarousel/BlockImageCarousel.js
Fixes a regression from #277. It was already fixed for some buttons in [this commit](https://github.com/nasa-jpl/explorer-1/pull/277/commits/13fab53aedb3 …
=> fix: adding icon-only flag to image carousel buttons

storybook/stories/_docs/foundation_typography.stories.mdx, storybook/stories/components/BaseHeading/BaseHeading.js, storybook/stories/components/BaseHeading/BaseHeading.stories.js
Implements the new "headings with icons" pattern, via a utility class rather than a specific component. I chose this approach because it’s the simplest and seemed sufficient. The vertical alignment between the icon and text isn’t always perfect but I’d say it’s worth adjusting case-by-case based on the specific visuals of the icon.
I’ve added two sets of examples:
- In foundation stories, with a single icon that’s a good approximation of the kind of visual that could be next to a heading
- In BaseHeading stories, with three different icons that represent different possible formats (high, wide, square)
=> Add examples of headings with icons

apps/vue-storybook/package.json, packages/common-storybook/package.json, packages/common/package.json, packages/configs/eslint/index.js, packages/configs/eslint/package.json, packages/html/package.json, packages/html/src/components/AppBarInternal/AppBarInternal.stories.js, packages/html/src/components/BaseButton/BaseButton.js, packages/html/src/components/MixinCarousel/MixinCarousel.js, packages/html/src/docs/utils/ComponentItem.jsx, packages/html/src/docs/utils/ComponentList.jsx, packages/nuxt/package.json, packages/vue/package.json, pnpm-lock.yaml
removes non-needed linting, removes redundant packages, fixes storybook rules
=> fixes eslinting rules for storybook

packages/vue/package.json, packages/vue/src/components/CalendarButton/CalendarButton.vue, packages/vue/src/components/SearchResultsList/SearchResultsList.vue, packages/vue/src/utils/mixins.ts
Fixes after testing with published package.
=> minor fixes for pnpm publish

eslint.config.js, packages/common/package.json, packages/vue/package.json, packages/vue/src/utils/dayjs.js, pnpm-lock.yaml
- Moving tailwindcss from `devDependencies` to `dependencies` in `@explorer-1/common`
- adding file type endings to dayjs imports in @explorer-1/vue
=> adjusting dependencies for explorer-1/common

packages/vue/src/components/CalendarButton/CalendarButton.vue, packages/vue/src/components/MissionDetailStats/DistanceStats.vue, packages/vue/src/components/SearchResultsList/SearchResultsList.vue
Reverts #479. When testing with WWW, I was running into errors. I also referenced this discussion thread: …
=> fix/Revert #479

packages/vue/package.json, packages/vue/src/components/BackToTop/BackToTop.vue, packages/vue/src/components/MissionDetailHighlights/MissionDetailHighlights.vue, packages/vue/src/components/NavDesktop/NavDesktopDropdownContent.vue, packages/vue/src/components/NavDesktop/NavDesktopDropdownMore.vue, packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue, packages/vue/src/templates/edu/PageEduNewsDetail.vue
Similar to our dayjs fix, where we need to add the file extension to the import.
=> fixing lodash imports for cjs

packages/common/src/scss/_typography.scss, packages/common/src/scss/components/_BlockTable.scss, packages/common/tailwind.config.ts, packages/vue/src/components/BlockTable/BlockTable.vue
`_BlockTable.scss` was originally importing all of `typography.scss` to be able to use the `.text-subtitle` class in an `@apply` statement.
This was, in …
=> Fix: changing strategy when using `text-subtitle` with `@apply` in `_BlockTable.scss`

packages/vue/src/templates/PageContent/PageContent.vue, packages/vue/src/templates/edu/PageContentEdu.stories.js, packages/vue/src/templates/edu/PageEduNewsDetail.vue
Fixes the `PageContent` component to use EDU share buttons when using the EDU theme.
Chromatic links coming soon
=> fix: share buttons on edu content pages

packages/vue/src/components/BaseHeading/BaseHeading.vue, packages/vue/src/components/BlockHeading/BlockHeading.vue, packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
Fixes #501 
When migrating the BaseHeading component from Vue 2 to Vue 3, I set a default size of `h2`. This should have been left blank. This PR fixes …
=> fix: remove default size from BaseHeading

packages/vue/package.json, packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue, packages/vue/src/components/NavSecondary/NavSecondary.vue
- Fixes the z-index on secondary nav menus to not overlap main menu dropdowns.
- Fixes some styles for the main nav in the EDU theme
=> Fix: secondary nav z-index, main edu nav styles

packages/vue/package.json, packages/vue/src/components/BlockVideoEmbed/BlockVideoEmbed.stories.js, packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue, packages/vue/src/templates/edu/PageEduResourceArticle/PageEduResourceArticle.vue
Follow up to #492. The computed `heroInline` value was not accounting for `VideoEmbedBlock`. This PR fixes that and effectively forces an inline layout …
=> fixing logic for VideoEmbedBlock in resource article page

packages/vue/src/components/NavSecondary/NavSecondary.vue
Supports https://github.com/nasa-jpl/www/issues/244
Modifies secondary nav styles to have the correct offset when scrolling up (the EDU header is …
=> fix: modifying offset of secondary nav for edu

packages/vue/src/components/ShareButtonsEdu/ShareButtonsEdu.vue, packages/vue/src/utils/mixins.ts
Supports https://github.com/nasa-jpl/www/issues/241
- adds the necessary url prefix for google classroom
- modifies `mixinCanonicalUrl` to gracefully …
=> fix google classroom share link

packages/vue/src/components/NavSecondary/NavSecondary.vue, packages/vue/src/utils/filters.js
Supports https://github.com/nasa-jpl/www/issues/244
- difficult to test without using the www frontend app (requires publishing the npm package for …
=> fix: secondary nav offset, dayjs import in utils/filters.js

packages/vue/package.json, packages/vue/src/components/BlockImage/BlockImageFullBleed.vue, packages/vue/src/components/BlockImage/BlockImageStandard.vue, packages/vue/src/components/BlockImageCarousel/BlockImageCarousel.stories.js, packages/vue/src/components/BlockImageCarousel/BlockImageCarousel.vue, packages/vue/src/components/BlockImageCarouselItem/BlockImageCarouselItem.vue, packages/vue/src/components/BlockImageGallery/BlockImageGallery.vue, packages/vue/src/components/BlockInlineImage/BlockInlineImage.vue, packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue, packages/vue/src/components/DetailHeadline/DetailHeadline.stories.js, packages/vue/src/components/DetailHeadline/DetailHeadline.vue, packages/vue/src/templates/PageImageDetail/PageImageDetail.stories.js, packages/vue/src/templates/PageImageDetail/PageImageDetail.vue, packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.stories.js, packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue, packages/vue/src/templates/www/PageInfographicDetail/PageInfographicDetail.vue
Addresses most items from https://github.com/nasa-jpl/www/issues/28#issuecomment-2249082780
- Fixes bug when trying to render some News pages (issue …
=> fix: news detail page

package.json, packages/vue/package.json, packages/vue/src/components/DetailHeadline/DetailHeadline.stories.js, packages/vue/src/components/DetailHeadline/DetailHeadline.vue, packages/vue/src/templates/PageNewsDetail/PageNewsDetail.stories.js, packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue, packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.stories.js, packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue, packages/vue/src/templates/edu/PageEduResourceArticle/PageEduResourceArticle.stories.js, packages/vue/src/templates/edu/PageEduResourceArticle/PageEduResourceArticle.vue
Follow-up to https://github.com/nasa-jpl/www/issues/28
Adds support for `readTime` to `DetailHeadline` and configures its use on `PageNewsDetail`, …
=> Adds readTime to EDU News, EDU explainer articles, and WWW news

packages/common/src/scss/_print.scss, packages/common/src/scss/components/_BlockKeyPoints.scss, packages/common/src/scss/styles.scss, packages/vue/src/components/BaseButton/BaseButton.vue, packages/vue/src/components/BaseImage/BaseImage.vue, packages/vue/src/components/BaseTag/BaseTag.vue, packages/vue/src/components/BlockIframeEmbed/BlockIframeEmbed.vue, packages/vue/src/components/BlockImage/BlockImageStandard.vue, packages/vue/src/components/BlockKeyPoints/BlockKeyPoints.vue, packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/components/BlockRelatedLinks/BlockRelatedLinks.vue, packages/vue/src/components/BlockRelatedLinks/RelatedLink.vue, packages/vue/src/components/BlockVideo/BlockVideo.vue, packages/vue/src/components/BlockVideoEmbed/BlockVideoEmbed.vue, packages/vue/src/components/EventDetailHero/EventDetailHero.vue, packages/vue/src/components/HeroMedia/HeroMedia.vue, packages/vue/src/components/MixinCarousel/MixinCarousel.vue, packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue, packages/vue/src/components/NavMobile/NavMobile.vue, packages/vue/src/components/ShareButtons/ShareButtons.vue, packages/vue/src/components/ShareButtonsEdu/ShareButtonsEdu.vue, packages/vue/src/components/TheFooter/TheFooter.vue, packages/vue/src/templates/PageEventDetail/PageEventDetail.vue, packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue, packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
Supports https://github.com/nasa-jpl/www/issues/223
2. view isolated stories: example: …
=> Feature: Adding boilerplate print styles

packages/vue/src/components/NavMobile/NavMobile.vue, packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.stories.js, packages/vue/src/utils/mixins.ts
- uses a consistent style of spaces and dashes when event dates and times span multiple days or hours
- unsticks nav in print styles
=> fix: minor adjustments to release 3.2.7

packages/vue/src/components/BaseTimer/BaseTimer.vue, packages/vue/src/components/HeroLarge/HeroLarge.stories.js, packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.stories.js, packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue, packages/vue/src/templates/PageVideoDetail/PageVideoDetail.stories.js, packages/vue/src/templates/PageVideoDetail/PageVideoDetail.vue, packages/vue/src/templates/www/PageAsteroidWatchIndex/PageAsteroidWatchIndex.stories.js, packages/vue/src/templates/www/PageAsteroidWatchIndex/PageAsteroidWatchIndex.vue, packages/vue/src/templates/www/PageInfographicDetail/PageInfographicDetail.stories.js, packages/vue/src/templates/www/PageInfographicDetail/PageInfographicDetail.vue, packages/vue/src/templates/www/PagePodcastSeason/PagePodcastSeason.stories.js, packages/vue/src/templates/www/PagePodcastSeason/PagePodcastSeason.vue, packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.vue, packages/vue/src/templates/www/PageTopicDetail/PageTopicDetail.stories.js, packages/vue/src/templates/www/PageTopicDetail/PageTopicDetail.vue
Field name was incorrect for several listing page heroes.
=> fixing listing page hero images

packages/vue/src/components/BaseTimer/BaseTimer.vue, packages/vue/src/components/NavSearchForm/NavSearchForm.vue, packages/vue/src/components/PastEventsCarousel/PastEventsCarousel.vue, packages/vue/src/utils/dayjs.js
Dayjs was never fully fixed and throwing errors in `BaseTimer`. 
This PR also converts `NavSearchForm` to use the composition API.
1. use this branch …
=> Fixing dayjs imports, use composition API in NavSearchForm

package.json, packages/vue/package.json, packages/vue/src/components/BaseTimer/BaseTimer.vue, packages/vue/src/utils/dayjs.js
Follow up to #543. Moving all dayjs extensions in BaseTimer to base dayjs config.
=> Fixing BaseTimer

packages/vue/src/components/BaseTimer/BaseTimer.vue, packages/vue/src/utils/dayjs.js
Started getting the below error persisting on www:
```
SyntaxError: The requested module '/_nuxt/node_modules/dayjs/plugin/advancedFormat.js?v=dac44595' does not provide an export named 'default' (at dayjs.js?v=dac44595:5:8)
```
This PR fixes it, but I've only been able to test locally.
=> moving BaseTimer dayjs config to main dayjs config

packages/common/src/scss/_typography.scss, packages/common/src/scss/components/_BlockText.scss, packages/common/tailwind.config.ts, packages/vue/src/docs/foundation/typography.stories.js
Addresses https://github.com/nasa-jpl/www/issues/286 and https://github.com/nasa-jpl/www/issues/387
2. math text can be seen at …
=> adding math text styles, using primary color for BlockText lists

packages/common/src/scss/_grid.scss, packages/vue/src/constants.ts, packages/vue/src/interfaces.ts, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue, packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue, packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js, packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Supports https://github.com/nasa-jpl/www/issues/101
Adds the PageEduTeachableMoment template
2. view the story: …
=> feature: PageEduTeachableMoment template

packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
Implements the CSS solution mentioned in https://github.com/nasa-jpl/www/issues/413
=> Proof of concept: CSS solution to continuous ordered lists in EDU Lesson Procedures

packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue, packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue, packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.vue
Addresses feedback from https://github.com/nasa-jpl/www/issues/225#issuecomment-2305450019
2. View the `BlockStreamfield` story. …
=> fixing alignment of BlockCardGrid in streamfields

packages/vue/src/components/BaseAccordionItem/BaseAccordionItem.vue
Noticed discrepancies in BlockAccordion from the original block when reviewing feedback for https://github.com/nasa-jpl/www/issues/379.
This PR fixes …
=> tweaking styles of accordion item header to match original block

packages/vue/src/components/CalendarButton/CalendarButton.vue, packages/vue/src/utils/dayjs.js
Address feedback in https://github.com/nasa-jpl/www/issues/319#issuecomment-2299936254
Approach: I didn't hide the button for events with no time. …
=> fix: ICS for events with no time

packages/vue/src/components/AboutTheAuthor/AboutTheAuthor.vue, packages/vue/src/interfaces.ts, packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue, packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue, packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue, packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js, packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Address most of the feedback from https://github.com/nasa-jpl/www/issues/101#issuecomment-2313411674
- adds readTime to teachable moments
- fixes jump …
=> Fixing feedback on Teachable Moments template

packages/vue/src/components/NavDesktop/NavDesktop.vue, packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue, packages/vue/src/components/NavSecondary/NavSecondary.vue, packages/vue/src/utils/mixins.ts
Address latest feedback in https://github.com/nasa-jpl/www/issues/189
Fixes `checkActive` function to handle both a path and a full url when checking …
=> nav: fixing active section logic, fixing global nav breadcrumbs interfering with JumpNav

packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue, packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
Supports https://github.com/nasa-jpl/www/issues/413
- Revises data structure for lesson procedures
- When using steps numbering, the first item in the …
=> revising data model for EDU Lesson procedures

packages/common/src/scss/components/_BlockText.scss, packages/vue/src/components/BlockHeading/BlockHeading.vue, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue, packages/vue/src/utils/mixins.ts
Address feedback from https://github.com/nasa-jpl/www/issues/99#issuecomment-2303862870
- fixes scroll margin for anchor linked headings
- fixes section …
=> QA fixes for EDU Lesson Page 

packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue, packages/vue/src/templates/edu/PageEduMultimediaDetail/PageEduMultimediaDetail.vue
- fixes custom captions on images in the EDU Gallery template
- fixes video caption in EDU Multimedia template
=> fixing minor issues on multimedia templates

packages/vue/src/components/BasePill/BasePill.vue, packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.vue, packages/vue/src/components/DetailHeadline/DetailHeadline.vue, packages/vue/src/components/HeroLarge/HeroLarge.vue, packages/vue/src/components/HeroMedium/HeroMedium.vue, packages/vue/src/components/SearchResultCard/SearchResultCard.vue, packages/vue/src/components/SearchResultsList/SearchResultsList.vue, packages/vue/src/constants.ts, packages/vue/src/interfaces.ts, packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
Addresses part of https://github.com/nasa-jpl/www/issues/272
- Adds Event metadata to elastic search results
- Does not add Event filters (see …
=> adding mapping for edu events and elastic search

packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue, packages/vue/src/components/SearchResultCard/SearchResultCard.vue, packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue, packages/vue/src/constants.ts, packages/vue/src/utils/lookupContentType.ts
- integrates `prettyFilterNames` into a new `lookupContentType` method that can convert between interface name (`EDUImageDetailPage`), model name …
=> Cleans up logic for switching between different content type aliases, adds EDU Search keys

packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.vue, packages/vue/src/components/CalendarChip/CalendarChip.vue, packages/vue/src/components/Icons/IconCalendar.vue, packages/vue/src/components/SearchResultCard/SearchResultCard.vue, packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue, packages/vue/src/components/SearchResultsList/SearchResultsList.vue, packages/vue/src/utils/mixins.ts
Address the following feedback:
- https://github.com/nasa-jpl/www/issues/272#issuecomment-2322339587
- …
=> fixes from feedback on edu events and news listing pages

packages/common/src/scss/_grid.scss, packages/vue/src/components/BaseCarousel/BaseCarousel.vue, packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/components/HeroListingIndex/HeroListingIndex.stories.js, packages/vue/src/components/HeroListingIndex/HeroListingIndex.vue, packages/vue/src/components/HeroMedium/HeroMedium.vue, packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue, packages/vue/src/components/MetadataEvent/MetadataEvent.stories.js, packages/vue/src/components/MetadataEvent/MetadataEvent.vue, packages/vue/src/components/NavDesktop/NavDesktop.vue, packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue, packages/vue/src/components/NavMobile/NavMobile.vue, packages/vue/src/components/NewsDetailMediaContact/NewsDetailMediaContact.vue, packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue, packages/vue/src/components/SearchResultCard/SearchResultCard.vue, packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue, packages/vue/src/components/SearchResultsList/SearchResultsList.vue, packages/vue/src/interfaces.ts, packages/vue/src/templates/www/PageTimeline/PageTimeline.vue, packages/vue/src/utils/mixins.ts
Supports:
- https://github.com/nasa-jpl/www/issues/296
Changes:
- Several enhancements to support metadata on the EDU Resource Library index page
- Also …
=> feature: edu resource library index page

.github/workflows/storybook.yml, packages/common/src/scss/components/_BlockText.scss, packages/vue/src/components/BaseImageCaption/BaseImageCaption.vue, packages/vue/src/components/BlockImage/BlockImageFullBleed.vue, packages/vue/src/components/BlockImage/BlockImageStandard.vue, packages/vue/src/components/BlockImageComparison/BlockImageComparison.vue, packages/vue/src/components/BlockText/BlockText.vue, packages/vue/src/components/BlockVideo/BlockVideo.vue, packages/vue/src/components/BlockVideoEmbed/BlockVideoEmbed.vue, packages/vue/src/components/DetailHeadline/DetailHeadline.vue, packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.stories.js, packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue, packages/vue/src/templates/edu/PageEduMultimediaDetail/PageEduMultimediaDetail.vue
Addresses QA feedback for:
- https://github.com/nasa-jpl/www/issues/441#issuecomment-2322200346
- https://github.com/nasa-jpl/www/issues/442
- …
=> fix: edu resource multimedia and gallery templates

packages/vue/src/components/BaseLink/BaseLink.vue
adds a filter to `BaseLink` to filter out the unnecessary `/home/` prefix from wagtail default site urlPaths
=> fix: removing `/home/` prefix from BaseLink

apps/vue-storybook/.storybook/_mock-components.js, packages/vue/package.json, packages/vue/src/components/BlockImageComparison/BlockImageComparison.vue, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue, packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue, pnpm-lock.yaml
Addresses QA from:
- https://github.com/nasa-jpl/www/issues/99#issuecomment-2318156030
Also adds `<ClientOnly>` back to `BlockImageComparison` and …
=> fixes: Lesson Template and ClientOnly

packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js, packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue, packages/vue/src/utils/generateHash.ts
Follow up to:
- https://github.com/nasa-jpl/www/issues/99#issuecomment-2318156030
- Ensures that a heading will not appear in the Jump Menu navigation …
=> fixing headings in edu lesson jump menus, adding generateHash

packages/vue/src/components/BlockTeaser/BlockTeaser.vue, packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/441#issuecomment-2338615606
Changes:
- Fixes pill label and color on EDU Gallery detail pages
- …
=> fix: Gallery Detail Page and BlockTeaser

packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js, packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue, packages/vue/src/components/MetadataEvent/MetadataEvent.vue, packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue, packages/vue/src/components/SearchResultCard/SearchResultCard.stories.js, packages/vue/src/components/SearchResultsList/SearchResultsList.vue
- https://github.com/nasa-jpl/www/issues/272#issuecomment-2339336806
- https://github.com/nasa-jpl/www/issues/296#issuecomment-2339420586
- https://github.com/nasa-jpl/www/issues/529
Changes:
- Event metadata in BlockLinkCard will now accurately show calendar chip in search results
- When `BlockLinkCard` is `compact`, resource metadata will hide the time if audience and subject are populated
- Adjusts text size of metadata in a compact `BlockLinkCard` at different viewports
- Allows metadata to wrap in a compact `BlockLinkCard`
=> fixing date metadata in edu event search results

packages/vue/src/components/SearchInput/SearchInput.vue, packages/vue/src/templates/edu/PageEduHome/PageEduHome.stories.js, packages/vue/src/templates/edu/PageEduHome/PageEduHome.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/287
- https://github.com/nasa-jpl/www/issues/321
Does not include hot_topics functionality to click …
=> adding EDU Home page template

packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.stories.js, packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue, packages/vue/src/components/SearchFilterGroupAccordionItem/SearchFilterGroupAccordionItem.vue, packages/vue/src/interfaces.ts, packages/vue/src/templates/PageImageDetail/PageImageDetail.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/466
In cojunction with (many of these changes required updating …
=> feature: edu resource subjects accordion filter group

packages/vue/src/components/PodcastSeriesCarousel/PodcastSeriesCarousel.vue, packages/vue/src/templates/PageAudioDetail/PageAudioDetail.vue, packages/vue/src/templates/PageImageDetail/PageImageDetail.vue, packages/vue/src/templates/www/PagePodcast/PagePodcast.vue, packages/vue/tsconfig.json
Fixes the following error on Podcast episode and season pages:
```
500 Cannot assign to read only property '0' of object '[object Array]'
```
=> fix: use of .sort() in Podcast templates

packages/vue/src/components/BlockHeading/BlockHeading.vue, packages/vue/src/components/NavMobile/NavMobile.vue, packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue, packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue, packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue, packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
- https://github.com/nasa-jpl/www/issues/96#issuecomment-2347134746
Changes:
- fixes anchor links on student project steps
- fixes …
=> fix: student projects template feedback

packages/vue/src/components/NavSecondary/NavSecondary.vue
Fixes a v3 regression on NavSecondary borders . When scrolling down, secondary navigation should have a bottom border. 
- easiest to test with content …
=> fixing border in NavSecondary

packages/vue/src/components/BlockHeading/BlockHeading.vue, packages/vue/src/components/NavJumpMenu/NavJumpMenu.stories.js, packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue, packages/vue/src/components/NavSecondary/NavSecondaryDropdownContent.vue
- https://github.com/nasa-jpl/www/issues/172#issuecomment-2354347969
Changes:
- differentiates between router and regular links in …
=> fix: anchor links in mobile nav, long menus in Jump Nav

packages/common/src/scss/components/_BlockRichTable.scss, packages/vue/src/components/BlockRichTable/BlockRichTable.stories.js, packages/vue/src/components/BlockRichTable/BlockRichTable.vue
- https://github.com/nasa-jpl/www/issues/171#issuecomment-2370104633
Changes:
- Changes EDU BlockRichTable header row to use …
=> fix: EDU BlockRichTable adjustments

packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js, packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/constants.ts
- https://github.com/nasa-jpl/www/issues/191#issuecomment-2322505407
Changes:
- Adds an external link icon next to the label for all …
=> fix: listing metadata for EDU News and External Links

packages/vue/src/components/BlockCardGrid/BlockCardGrid.stories.js, packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue, packages/vue/src/components/BlockImage/BlockImageFullBleed.vue, packages/vue/src/components/HeroMedia/HeroMedia.vue, packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
- https://github.com/nasa-jpl/www/issues/601#issue-2546642664
Changes:
- EDU NavDesktop will now expand to full-width
- Removed gray …
=> fix: full bleed adjustments

packages/vue/src/components/HomepageCarousel/HomepageCarousel.stories.js, packages/vue/src/components/HomepageCarousel/HomepageCarousel.vue, packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue
Fixes the WWW homepage carousel tabbed navigation:
- Tabbed items no longer cut off
- Tabbed items cycle through at the same time as the main slide
1. …
=> fix: www homepage carousel tabbed navigation

packages/vue/src/components/HeroMedia/HeroMedia.vue
Addresses issue:
- https://github.com/nasa-jpl/www/issues/620
Changes:
- Adds a width to the hero container
2. view …
=> fix: ensuring hero media is full-width

packages/vue/src/components/SearchFilterGroupAccordionItem/SearchFilterGroupAccordionItem.vue
- https://github.com/nasa-jpl/www/issues/466#issuecomment-2357307577
Changes:
- modifies padding and margin around filter group …
=> EDU: adjusting height of accordion filter groups to match non-accordions

packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Follow up to:
- #643 
- https://github.com/nasa-jpl/www/issues/217#issuecomment-2372154363
Determined the issue was due to the more specific rule taking precedence (though this only occurred on the server)
=> fix: rich text media on Student Projects

packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
Limiting the newly added `IconExternal` in `BlockLinkCard` to the EDU theme to minimize potential impact on WWW.
=> only showing IconExternal in BlockLinkCard for edu theme

packages/vue/src/components/NavSecondary/NavSecondary.vue, packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.stories.js, packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue
- https://github.com/nasa-jpl/www/issues/617
Changes
- Adds support for secondary nav on the EDU Collections template
- Adds …
=> feature: add support for secondary nav on EDU Collections template

packages/vue/src/components/BaseLink/BaseLink.vue, packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue, packages/vue/src/utils/isEduExternalLink.ts
Addresses:
- https://github.com/nasa-jpl/www/issues/619
Changes:
- Adds a utility function that determines whether a string should be considered an …
=> specifying what qualifies as an external link for EDU theme

packages/vue/src/components/BaseLink/BaseLink.vue
Adds a trailing slash to all links regardless if it's a router link or not. Checks urls for files and query params.
Not testable in Storybook as we use …
=> adding trailing slashes in BaseLink

packages/vue/src/components/BaseLink/BaseLink.vue, packages/vue/src/components/PastEventsCarousel/PastEventsCarousel.vue
- adding guard to `addTrailingSlash` in BaseLink
- changing link object to string in PastEventsCarousel
1. Test locally with www ([see instructions …
=> fix: path.includes is not a function

packages/vue/src/components/NavMobile/NavMobile.vue, packages/vue/src/components/NavSecondary/NavSecondary.vue, packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue, packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Fixes regressions (some introduced in https://github.com/nasa-jpl/explorer-1/pull/656/):
- https://github.com/nasa-jpl/www/issues/700
- …
=> fix: Various NavMobile and NavJumpMenu fixes for EDU

packages/common/src/scss/components/_BlockKeyPoints.scss, packages/common/src/scss/components/_BlockText.scss
Addresses:
- https://github.com/nasa-jpl/www/issues/699
Changes:
- Removes `content` from `::marker` rules and uses `list-style-type: '—'` instead
1. …
=> fix: using safari-supported method of defining list marker character

packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
Addresses
- https://github.com/nasa-jpl/www/issues/708
2. view a lesson story with a mobile viewport: …
=> applying indent to containing div of Lesson > Procedure > Step instead of list item

packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue, packages/vue/src/components/BlockCardGridItem/BlockCardGridItem.vue
Addresses:
- https://github.com/nasa-jpl/www/issues/746
Changes:
- adds `link` prop to mobile template for BlockCardGrid
- adds specific wrapper-class …
=> fix: passing link prop to mobile block link grid cards

.changeset/slimy-hairs-rush.md, packages/vue/src/components/HomepageTeaserBlock/HomepageTeaserBlock.vue, packages/vue/src/utils/mixins.ts
Fixes link logic in HomepageTeaserBlock by separating link logic between the card and main block. Fixes the link to the virtual tour on the homepage.
1. …
=> fixing link logic in HomepageTeaserBlock

.changeset/spotty-rockets-sit.md, packages/vue/src/components/BaseVideo/BaseVideo.vue, packages/vue/src/components/BlockVideo/BlockVideo.stories.js, packages/vue/src/components/BlockVideo/BlockVideo.vue, packages/vue/src/components/HeroMedia/HeroMedia.vue, packages/vue/src/components/MixinVideoBg/MixinVideoBg.stories.js, packages/vue/src/components/MixinVideoBg/MixinVideoBg.vue, packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
Supports:
- https://github.com/nasa-jpl/www-frontend/issues/1672
To test:
2. view the stories of changed components. Note that usage of `MixinVideoBg` in `HeroMedia` will always loop the video. This means the "autoplay" checkbox that appears to editors in this context has no effect (see https://github.com/nasa-jpl/www-backend/pull/1176)
=> Feature/1672 Video Block autoplay option

packages/vue/src/templates/PageNewsDetail/PageNewsDetail.stories.js, packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
Fixes a regression that occurred during the EDU update. On WWW news stories, hero videos can be full width or inline. Currently, they are being forced …
=> fix: allowing hero videos to be inline on news pages

packages/common/src/scss/components/_HeroMedia.scss, packages/vue/src/components/HeroMedia/HeroMedia.vue
Fixes a regression. `HeroMedia` will  now adjust height based on the viewport. This broke because a `div` was removed. The `div` has now been restored. …
=> Fix: restoring dynamic height in HeroMedia

packages/vue/src/components/HeroInlineMedia/HeroInlineMedia.vue, packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
Fixes https://github.com/nasa-jpl/www-frontend/issues/1728
Updates `BlockHeroInline` to use `BlockVideoEmbed` instead of `BaseImagePlaceholder` for …
=> Fix: Caption in Hero video embeds

packages/vue/src/components/BaseRadioGroup/BaseRadioGroup.vue, packages/vue/src/components/BlockNewsletterSignup/BlockNewsletterSignup.stories.js, packages/vue/src/components/BlockNewsletterSignup/BlockNewsletterSignup.vue, packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js, packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue, packages/vue/src/templates/PageContent/PageContent.vue
Adds a newsletter signup block (https://github.com/nasa-jpl/www-frontend/issues/1684) to Explorer 1. 
- This signup block is specific to the JPL …
=> Feature: Newsletter Signup block using form action

packages/common/src/scss/_components.scss, packages/common/src/scss/components/_BaseCarousel.scss, packages/common/src/scss/components/_HomepageCarousel.scss, packages/common/src/scss/components/_HomepageMissionsCarousel.scss, packages/common/src/scss/components/_MissionDetailHighlightsCarousel.scss, packages/common/src/scss/styles.scss, packages/vue/src/components/BlockAnchor/BlockAnchor.vue, pnpm-lock.yaml
@sfimbres I noticed that Storybook builds were no longer working, which seemed off to me. After a bit of debugging, I made a revision to [your earlier PR](https://github.com/nasa-jpl/explorer-1/pull/732) (apologies for missing these the first time around!)
- including `@import 'swiper/swiper-bundle.css';` in the component scss itself is problematic, and that import is already included in _vendors.scss, so I removed it from a few files
- some minor cleanup just to make things more consistent
=> Fix Storybook builds
